### ISSUE TITLE
Password field not focused

### ISSUE THREAD

**Issue by beojan** [MalditoBarbudo/solarized_sddm_theme#5]
Issue #4 still persists.

**Comment by MalditoBarbudo** [comment]
This is a issue in sddm, already fixed (see sddm/sddm#602), but not released yet (the milestone is sddm 0.14).
If you are using sddm 0.13 (the actual version of sddm) you have to wait until the next version. In the case you are using the development version of sddm and still not working let me know, as I made some tests and it was working without problems in my system.

(Edited: typo)

**Comment by beojan** [comment]
It appears to work with sddm-git.

**Comment by MalditoBarbudo** [comment]
Ok, thank you!.
I close the issue then.
